name = "DocQuantum's Osprey Delight"

license = "Apache License 2.0"
licenselink = "https://github.com/docquantum/docquantum-web-theme//blob/main/LICENSE.md"
description = "Blazingly fast and modular theme perfectly suited for showing your work."

homepage = "https://github.com/docquantum/docquantum-web-theme/"

tags = ["portfolio", "projects", "minimal", "personal", "landing", "onepage", "single-page", "hugo-mods", "responsive", "blog"]
features = [
  "gallery", "flexbox", # gallery/work portfolio
  "contact", "contact-form", # basin contact formular with spambot protection 
  "blog", # optional blog
  "scroll-spy", "background", "lazyload", "blur-up", "lqip", "webp", "image-processing", "asset-driven", "lazyimg", # technical features
  "github", "github-integration", "termynal", "social-icons", # some extras
  "structured-data", "opengraph", "pagespeed-insights", # seo
  "themeable", "hugo-mods", # customizability
]

[author]
  name = "DocQuantum"
  homepage = "https://docquantum.me/"

[original]
  name = "kdevo"
  homepage = "https://kdevo.github.io/"
  repo = "https://github.com/kdevo/osprey-delight/"